### PR TITLE
app: support for `oneOf` param scopings

### LINKED ISSUE #171: app: add support for `oneOf` comparison
The current app implementation was wrong, interpreting `oneOf` as a string contains. I temporarily disabled this comparison option until we have a working implementation.

When selecting `oneOf` the comparison value input actually must switch to a value list input.

### PR DESCRIPTION
**Pull request by jfschwarz**
closes #171 

based off #181, so should only be merged after that one

### CODE REVIEW

File: packages/app/src/components/views/Role/targets/TargetFunctionParams.tsx [hunk 1]
```diff
@@ -49,58 +53,68 @@ export const TargetFunctionParams = ({ func, funcConditions, disabled, onChange
...
+                  <Typography variant="body1">[{index}]</Typography>
+                  <Typography variant="body2" className={classes.type}>
+                    ({param.type})
+                  </Typography>
+                </div>
+                <ParamConditionInput
+                  disabled={disabled}
+                  param={null}
+                  index={index}
+                  condition={funcConditions.params.find((param) => param?.index === index)}
```
Comment (manboy-eth) [inline packages/app/src/components/views/Role/targets/TargetFunctionParams.tsx:80]:
```suggestion
                  condition={param}
```

**Review by manboy-eth — APPROVED** [review]
